In [2]:
import pandas

In [10]:
day1= pandas.read_parquet("E1a/SPO-DK0012R_00611_100.parquet")
day2= pandas.read_parquet("E1a/SPO-DK0012R_00617_100.parquet")

In [5]:
day1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Samplingpoint     59 non-null     object
 1   Pollutant         59 non-null     int32
 2   Start             59 non-null     datetime64[ns]
 3   End               59 non-null     datetime64[ns]
 4   Value             59 non-null     object
 5   Unit              59 non-null     object
 6   AggType           59 non-null     object
 7   Validity          59 non-null     int32
 8   Verification      59 non-null     int32
 9   ResultTime        59 non-null     datetime64[ns]
 10  DataCapture       0 non-null      object
 11  FkObservationLog  59 non-null     object
dtypes: datetime64[ns](3), int32(3), object(6)
memory usage: 5.0+ KB

In [8]:
day1.head()

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog
0,DK/SPO-DK0012R_00611_100,611,2016-01-01,2016-03-01,0.176000000000000000,ug.m-2.day-1,var,1,1,2017-09-26,None,a620620c-bbef-4cd3-a379-b3bba240ae43
1,DK/SPO-DK0012R_00611_100,611,2016-03-01,2016-05-01,0E-18,ug.m-2.day-1,var,2,1,2017-09-26,None,a620620c-bbef-4cd3-a379-b3bba240ae43
2,DK/SPO-DK0012R_00611_100,611,2016-05-01,2016-07-01,0E-18,ug.m-2.day-1,var,2,1,2017-09-26,None,a620620c-bbef-4cd3-a379-b3bba240ae43
3,DK/SPO-DK0012R_00611_100,611,2016-07-01,2016-09-01,0E-18,ug.m-2.day-1,var,2,1,2017-09-26,None,a620620c-bbef-4cd3-a379-b3bba240ae43
4,DK/SPO-DK0012R_00611_100,611,2016-09-01,2016-11-01,0E-18,ug.m-2.day-1,var,2,1,2017-09-26,None,a620620c-bbef-4cd3-a379-b3bba240ae43

In [11]:
day2.head()

,Samplingpoint,Pollutant,Start,End,Value,Unit,AggType,Validity,Verification,ResultTime,DataCapture,FkObservationLog
0,DK/SPO-DK0012R_00617_100,618,2024-01-01,2024-02-01,0.028000000000000000,ug.m-2.day-1,var,1,1,2025-09-22,None,2ce8f7ba-7f5a-4ee0-9773-7ada4e9461d6
1,DK/SPO-DK0012R_00617_100,618,2024-02-01,2024-03-01,0.018000000000000000,ug.m-2.day-1,var,1,1,2025-09-22,None,2ce8f7ba-7f5a-4ee0-9773-7ada4e9461d6
2,DK/SPO-DK0012R_00617_100,618,2024-03-01,2024-04-01,0.013000000000000000,ug.m-2.day-1,var,1,1,2025-09-22,None,2ce8f7ba-7f5a-4ee0-9773-7ada4e9461d6
3,DK/SPO-DK0012R_00617_100,618,2024-04-01,2024-05-01,0.014000000000000000,ug.m-2.day-1,var,1,1,2025-09-22,None,2ce8f7ba-7f5a-4ee0-9773-7ada4e9461d6
4,DK/SPO-DK0012R_00617_100,618,2024-05-01,2024-06-01,0E-18,ug.m-2.day-1,var,2,1,2025-09-22,None,2ce8f7ba-7f5a-4ee0-9773-7ada4e9461d6

In [9]:
day1.describe()

,Pollutant,Start,End,Validity,Verification,ResultTime
count,59.0,59,59,59.000000,59.0,59
mean,611.0,2020-11-21 15:51:51.864406784,2021-01-15 08:32:32.542372864,1.525424,1.0,2022-03-11 15:03:03.050847488
min,611.0,2016-01-01 00:00:00,2016-03-01 00:00:00,-1.000000,1.0,2017-09-26 00:00:00
25%,611.0,2018-08-01 00:00:00,2018-10-01 12:00:00,1.000000,1.0,2019-09-17 00:00:00
50%,611.0,2021-01-01 00:00:00,2021-03-01 00:00:00,2.000000,1.0,2022-09-15 00:00:00
75%,611.0,2023-05-31 12:00:00,2023-08-01 00:00:00,2.000000,1.0,2024-09-13 00:00:00
max,611.0,2024-12-01 00:00:00,2025-01-01 00:00:00,2.000000,1.0,2025-09-22 00:00:00
std,0.0,NaN,NaN,0.935063,0.0,NaN